### ISSUE TITLE
Use websocket sub-protocols to negotiate the encoding.

### ISSUE THREAD

**Issue by jmalloc** [rinq/websocket#1]
There is a [standard mechanism](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_servers#Subprotocols
) to negotiate the websocket "sub-protocol", which I would prefer to use over the custom AMQP-esque message exchange we do now.

I propose using a sub-protocol name in the format: `rinq/<major>.<minor>+<encoding>`, e.g. `rinq/1.0+cbor`. This is reminiscent of a mime type (which sub-protocols are not), and the part after the slash is also a valid semver version.

This also leaves us free to implement WAMP/JSON-RPC/etc in the future on the server-side, which would be useful for exposing public APIs for some of our cwx use-cases.

The IANA maintains a [registry of subprotocols](https://www.iana.org/assignments/websocket/websocket.xml#subprotocol-name). We can reserve these names once we're confident that they cover our needs.

**Comment by jmalloc** [comment]
Ok, slash `/` is not supported in the subprotocol name, so I'll roll with hypen `-`.

**Comment by ezzatron** [comment]
That's a shame. Be nice if it was a character that was less common in SemVer. Is there an RFC with the supported characters? What about `:`?

**Comment by ezzatron** [comment]
It could even be a valid URI then.

**Comment by jmalloc** [comment]
From the [WebSocket RFC](https://tools.ietf.org/html/rfc6455#page-12):

> The elements that comprise this value
        MUST be non-empty strings with characters in the range U+0021 to
        U+007E not including separator characters as defined in
        [RFC2616] and MUST all be unique strings.

And from RFC2616 about separators:

```
      separators     = "(" | ")" | "<" | ">" | "@"
                      | "," | ";" | ":" | "\" | <">
                      | "/" | "[" | "]" | "?" | "="
                      | "{" | "}" | SP | HT
```

The recommendation is to use the domain name prefixed with version `v1.rinq.io` but personally I prefer the idea of embedding the semver constraint `rinq-1.1+cbor`.

**Comment by jmalloc** [comment]
As discussed, we've rolled with `rinq-<major>.<minor>+<encoding>` on the server. I am not doing any semver parsing, the server simply accepts `rinq-1.0+cbor` or `rinq-1.0+json`.  We can worry about fallback-behaviour in the client if and when we get a v1.1.

**Comment by ezzatron** [comment]
As well as the usual unit tests, I've manually verified that this works against a JS dummy server, until we have the real thing to work with.
