### ISSUE TITLE
Move common message components out of the message header.

### ISSUE THREAD

**Issue by jmalloc** [rinq/websocket#3]
I've started getting a prototype of rinq/httpd together, specifically the "native rinq" protocol implementation.

I'd like to be able to unpack frames without the need to parse structured data (json or cbor) into an untyped / dynamic value. In order to do this in Go, and probably any statically-typed language the message type needs to be known before unpacking any structured data.

I am proposing moving the "common" part of the header to a "raw" binary encoding at the start of each frame, such that all frames begin the two-byte message type and an unsigned 16-bit session ID.

```
+--------+--------+--------+--------+
| 0      | 1      | 2      | 3      |
+--------+--------+--------+--------+
| type            | session ID      |
+-----------------+-----------------+
```

Frames that contain a header (everything except session create/destroy - `SC`/`SD`) would then follow this with the existing structure - an unsigned 16-bit header length followed be the structured header; optionally followed by a structured application payload.

```
+--------+--------+--------+--------+--------+--------+--------+---
| 0      | 1      | 2      | 3      | 4      | 5      | 6 ...  | n ...
+--------+--------+--------+--------+--------+--------+--------+---
| type            | session ID      | header length   | header | payload ...
+-----------------+-----------------+-----------------+--------+---
```

Call error responses (`CE`, `AE`) do not contain an application-payload, and as such do not *require* the header-length to split the header from the application payload, however I suggest retaining it for uniformity and future proofing.

All integer values use big-endian byte order.

An example "call async" frame, using `rinq-1.0+json` might be: 

```
CA\x00\x01\x00\x18["my-app","do-work",300]{"app-payload":"yes"}
```

**Comment by ezzatron** [comment]
Do you want me to take a stab at this?

**Comment by jmalloc** [comment]
I'd appreciate it sure, but no rush. There is plenty I can do server side yet if you don't get to it first.

**Comment by jmalloc** [comment]
I'm including our notes about the separation of preamble, header and application payload below.
I've altered the single-byte message types so all types are now two bytes (hence 16-bit int).

# Synchronous Command Calls
| Type     | Code | Header Fields                                 | Payload | Direction  |
| -        | -    | -                                             | -       | -          |
| Request  | `CC` | `seq int`, `ns str`, `cmd str`, `timeout int` | X       | cli -> svr |
| Error    | `CE` | `seq int`                                     |         | svr -> cli |
| Failure  | `CF` | `seq int`, `fail-type str`, `message str`     | X       | svr -> cli |
| Success  | `CS` | `seq int`,                                    | X       | svr -> cli |

# Asynchronous Command Calls
| Type    | Code | Header Fields                                       | Payload | Direction  |
| -       | -    | -                                                   | -       | -          |
| Request | `AC` | `ns str`, `cmd str`, `timeout int`                  | X       | cli -> svr |
| Error   | `AE` | `ns str`, `cmd str`                                 |         | svr -> cli |
| Failure | `AF` | `ns str`, `cmd str`, `fail-type str`, `message str` | X       | svr -> cli |
| Success | `AS` | `ns str`, `cmd str`                                 | X       | svr -> cli |

# Command Execution (no response)
| Type    | Code | Header Fields       | Payload | Direction  |
| -       | -    | -                   | -       | -          |
| Request | `CX` | `ns str`, `cmd str` | X       | cli -> svr |

# Notifications 
| Type         | Code | Header Fields | Payload | Direction  |
| -            | -    | -             | -       | -          |
| Notification | `NO` | `type str`    | X       | svr -> cli |

# Session Management
| Type    | Code | Header Fields | Payload | Direction  |
| -       | -    | -             | -       | -          |
| Create  | `SC` | (none)        |         | cli -> svr |
| Destroy | `SD` | (none)        |         | omni       |
