### ISSUE TITLE
Update tagline and descriptions simultaneously

### ISSUE THREAD

**Issue by ezzatron** [rinq/websocket#4]
The tagline was updated to `Rinq sessions in the browser.`, but the `package.json` description and `README.md` taglines didn't match, so I've changed it back for now. If we're gonna change it, let's change it in tandem.

**Comment by jmalloc** [comment]
No probs, but for what it's worth I don't think they are the same thing.  `package.json` should make sense in the context of the NPM website or command line tool. Whereas the package description is shown when you're already in the context of the `Rinq` organisation.
